version: "3.9"
services:
  nginx:
    build: ./nginx
    image: ghcr.io/serdcebolit/nginx:latest

  mysql:
    build: ./mysql
    image: ghcr.io/serdcebolit/mysql:latest

  deploy_manager:
    build: ./deploy_manager
    image: ghcr.io/serdcebolit/deploy_manager:latest

  sshproxy_gen:
    build: ./sshproxy
    image: ghcr.io/serdcebolit/sshproxy-gen:latest

  bx_installer:
    build: ./bx_installer
    image: ghcr.io/serdcebolit/bx_installer:latest

  adminer:
    build: ./adminer
    image: ghcr.io/serdcebolit/adminer:latest

#образы без xdebug
  backend70:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 70
    image: ghcr.io/serdcebolit/httpd:70

  backend71:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 71
    image: ghcr.io/serdcebolit/httpd:71

  backend72:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 72
    image: ghcr.io/serdcebolit/httpd:72

  backend73:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 73
    image: ghcr.io/serdcebolit/httpd:73

  backend74:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 74
    image: ghcr.io/serdcebolit/httpd:74

  backend80:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 80
    image: ghcr.io/serdcebolit/httpd:80

  backend81:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 81
    image: ghcr.io/serdcebolit/httpd:81

  backend82:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 82
    image: ghcr.io/serdcebolit/httpd:82

  backend83:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 83
    image: ghcr.io/serdcebolit/httpd:83

#образы с xdebug
  backend71-xdebug:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 71
        XDEBUG: php-pecl-xdebug
    image: ghcr.io/serdcebolit/httpd:71-xdebug

  backend72-xdebug:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 72
        XDEBUG: php-pecl-xdebug
    image: ghcr.io/serdcebolit/httpd:72-xdebug

  backend74-xdebug:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 74
        XDEBUG: php-pecl-xdebug
    image: ghcr.io/serdcebolit/httpd:74-xdebug

  backend80-xdebug:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 80
        XDEBUG: php-pecl-xdebug
    image: ghcr.io/serdcebolit/httpd:80-xdebug

  backend81-xdebug:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 81
        XDEBUG: php-pecl-xdebug
    image: ghcr.io/serdcebolit/httpd:81-xdebug

  backend82-xdebug:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 82
        XDEBUG: php-pecl-xdebug
    image: ghcr.io/serdcebolit/httpd:82-xdebug

  backend83-xdebug:
    build:
      context: ./httpd
      args:
        PHP_VERSION: 83
        XDEBUG: php-pecl-xdebug
    image: ghcr.io/serdcebolit/httpd:83-xdebug
