services:
  nginx:
    build: ./nginx
    image: nginx:latest

  mysql:
    build: ./mysql
    image: mysql:latest

  deploy_manager:
    build: ./deploy_manager
    image: ghcr.io/serdcebolit/deploy_manager

  sshproxy_gen:
    build: ./sshproxy
    image: sshproxy-gen:latest

  bx_installer:
    build: ./bx_installer
    image: bx_installer:latest

  adminer:
    build: ./adminer
    image: adminer:latest

#образы без xdebug
  backend70:
    build:
      context: ./httpd
      target: httpd_base
      args:
        PHP_VERSION: 70
    image: httpd:70

  backend71:
    build:
      context: ./httpd
      target: httpd_base
      args:
        PHP_VERSION: 71
    image: httpd:71

  backend72:
    build:
      context: ./httpd
      target: httpd_base
      args:
        PHP_VERSION: 72
    image: httpd:72

  backend73:
    build:
      context: ./httpd
      target: httpd_base
      args:
        PHP_VERSION: 73
    image: httpd:73

  backend74:
    build:
      context: ./httpd
      target: httpd_base
      args:
        PHP_VERSION: 74
    image: httpd:74

  backend80:
    build:
      context: ./httpd
      target: httpd_base
      args:
        PHP_VERSION: 80
    image: httpd:80

  backend81:
    build:
      context: ./httpd
      target: httpd_base
      args:
        PHP_VERSION: 81
    image: httpd:81

  backend82:
    build:
      context: ./httpd
      target: httpd_base
      args:
        PHP_VERSION: 82
    image: httpd:82

  backend83:
    build:
      context: ./httpd
      target: httpd_base
      args:
        PHP_VERSION: 83
    image: httpd:83

#образы с xdebug
  backend71-xdebug:
    build:
      context: ./httpd
      target: httpd_xdebug
      args:
        PHP_VERSION: 71
    image: httpd:71-xdebug

  backend72-xdebug:
    build:
      context: ./httpd
      target: httpd_xdebug
      args:
        PHP_VERSION: 72
    image: httpd:72-xdebug

  backend74-xdebug:
    build:
      context: ./httpd
      target: httpd_xdebug
      args:
        PHP_VERSION: 74
    image: httpd:74-xdebug

  backend80-xdebug:
    build:
      context: ./httpd
      target: httpd_xdebug
      args:
        PHP_VERSION: 80
    image: httpd:80-xdebug

  backend81-xdebug:
    build:
      context: ./httpd
      target: httpd_xdebug
      args:
        PHP_VERSION: 81
    image: httpd:81-xdebug

  backend82-xdebug:
    build:
      context: ./httpd
      target: httpd_xdebug
      args:
        PHP_VERSION: 82
    image: httpd:82-xdebug

  backend83-xdebug:
    build:
      context: ./httpd
      target: httpd_xdebug
      args:
        PHP_VERSION: 83
    image: httpd:83-xdebug
