name: Production Deploy

on:
  push:
    branches: [master]
  workflow_run:
    workflows: [Docker Image Builder]
    branches: [master]
    types:
      - completed

jobs:
  deploy:
    name: Деплой на сервер
    runs-on: ubuntu-latest
    needs: [ docker-build ]
    if: secrets.NEED_DEPLOY == 'true'
    steps:
      - name: Пул Докер образов, git pull и перезапуск сервера
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            cd ${{ secrets.DOCKER_ENV_PATH }}
            zsh sandbox stop
            git reset --hard
            git pull
            docker-compose -f docker-compose.build.yml pull
            zsh sandbox start